CREATE TABLE Hospital (
  CNPJ VARCHAR(14) NOT NULL UNIQUE,
  nome VARCHAR(50) NOT NULL,
  endereco VARCHAR(127) NOT NULL,
  PRIMARY KEY (CNPJ)
);

CREATE TABLE Medico (
  CRM VARCHAR(6) NOT NULL UNIQUE,
  nome VARCHAR(50) NOT NULL,
  hospitalCNPJ VARCHAR(14),
  PRIMARY KEY (CRM),
  FOREIGN KEY (hospitalCNPJ) REFERENCES Hospital (CNPJ) ON DELETE CASCADE
);

CREATE TABLE Especialidade (
  ID INTEGER NOT NULL UNIQUE,
  nome VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE MedicoEspecialidade (
  medicoCRM VARCHAR(6) NOT NULL,
  especialidadeID INTEGER NOT NULL,
  PRIMARY KEY (medicoCRM, especialidadeID),
  FOREIGN KEY (medicoCRM) REFERENCES Medico (CRM) ON DELETE CASCADE,
  FOREIGN KEY (especialidadeID) REFERENCES Especialidade (ID) ON DELETE CASCADE
);

CREATE TABLE Paciente (
  CPF VARCHAR(11) NOT NULL UNIQUE,
  nome VARCHAR(50) NOT NULL,
  PRIMARY KEY (CPF)
);

CREATE TABLE Consulta (
  ID INTEGER NOT NULL UNIQUE,
  data DATE NOT NULL,
  hora TIME NOT NULL,
  diagnostico VARCHAR(255) NOT NULL,
  medicoCRM VARCHAR(6) NOT NULL,
  pacienteCPF VARCHAR(11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (medicoCRM) REFERENCES Medico (CRM) ON DELETE CASCADE,
  FOREIGN KEY (pacienteCPF) REFERENCES Paciente (CPF) ON DELETE CASCADE
);

CREATE TABLE Exame (
  ID INTEGER NOT NULL UNIQUE,
  descricao VARCHAR(50) NOT NULL,
  data DATE NOT NULL,
  valor REAL NOT NULL,
  consultaID INTEGER,
  medicoCRM VARCHAR(6),
  PRIMARY KEY (ID),
  FOREIGN KEY (consultaID) REFERENCES Consulta (ID) ON DELETE CASCADE,
  FOREIGN KEY (medicoCRM) REFERENCES Medico (CRM) ON DELETE CASCADE
);
