DROP TABLE IF EXISTS Hospital;
DROP TABLE IF EXISTS Medico;
DROP TABLE IF EXISTS Especialidade;
DROP TABLE IF EXISTS MedicoEspecialidade;
DROP TABLE IF EXISTS Paciente;
DROP TABLE IF EXISTS Consulta;
DROP TABLE IF EXISTS Exame;
